# Generated by Django 4.1.3 on 2023-11-14 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Title')),
                ('author', models.CharField(max_length=255, verbose_name='Author')),
                ('content', models.TextField(verbose_name='Content')),
                ('rating_points', models.IntegerField()),
                ('field', models.CharField(choices=[('physics', 'Physics'), ('chemistry', 'Chemistry'), ('economics', 'Economics'), ('history', 'History'), ('math', 'Math'), ('biology', 'Biology'), ('machine learning', 'Machine Learning')], max_length=100, verbose_name='Field')),
            ],
        ),
    ]
