# Generated by Django 4.1.3 on 2023-11-14 13:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articles',
            options={'verbose_name': 'Article', 'verbose_name_plural': 'Articles'},
        ),
        migrations.RemoveField(
            model_name='articles',
            name='author',
        ),
        migrations.AddField(
            model_name='articles',
            name='authors',
            field=models.CharField(default=django.utils.timezone.now, max_length=500, verbose_name='Authors'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='articles',
            name='publication_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
