# Generated by Django 4.1.3 on 2023-11-14 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_articles_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='field',
            field=models.CharField(choices=[('Physics', 'Physics'), ('Chemistry', 'Chemistry'), ('Economics', 'Economics'), ('Math', 'Math'), ('Biology', 'Biology'), ('Machine Learning', 'Machine Learning')], max_length=100, verbose_name='Field'),
        ),
    ]
