# Generated by Django 4.1.3 on 2023-12-09 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_articles_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='pdf_file',
            field=models.FileField(default=None, upload_to='papers/'),
            preserve_default=False,
        ),
    ]
